### ISSUE TITLE
about train

### ISSUE THREAD

**Issue by JWSunny** [cftang0827/pedestrian_detection_ssdlite#1]
hello：
 thanks for your sharing, can you provide some messeages about mobilenet ssdlite using tensorflow, most codes use caffe, can you provide the train code using tensorflow, thanks.

**Comment by fuaiguo** [comment]
Thanks for your sharing, but can you provide the train code using tensorflow ?

**Comment by cftang0827** [comment]
Hi, in fact, I use Tensorflow object detection API for training, and I think the post is good.

https://github.com/tensorflow/models/tree/master/research/object_detection
Also, I would provide my training code and the person data extraction from VOC dataset code later.
If you think the model is useful, please kindly give me a Github star!
Thanks.

**Comment by cftang0827** [comment]
Hi, I had already uploaded some information. please take a look. Thanks. :)
